### ISSUE TITLE
Feature request: URL to clipboard

### ISSUE THREAD

**Issue by windrag** [nrj/OneWay#12]
Could be implemented in a number of ways:

a) URL is copied to clipboard automatically on file upload;
b) Copy URL to Clipboard button in OneWay Transfer window;
c) Select file in Transfer window and either ctl+click and choose Copy URL or cmd+c to copy URL (or  Edit menu command)

**Comment by nrj** [comment]
I really want to implement this feature. However I'm not sure how to do it with an upload that is multiple files and/or folders. My idea is to add a "Base URL" property to bookmarks that a user can optionally add (not all bookmarks are web servers). Then, if the user uploads a single file, and I have a base URL I can easily construct a URL to the file. But what if the user uploads 5 files, or 100 files in a single upload?

**Comment by windrag** [comment]
One idea:

1) Single file upload
        -copy URL
2) Multiple file upload
        -checkbox in preferences
            [•]When uploading multiple files, copy directory URL
        Otherwise, copy all URLs, one per line
3) Single directory (folder) upload
        -Copy folder URL
4) Multiple folder upload
        -Respects preferences for multiple file upload behavior

**Comment by nrj** [comment]
I've done some work on this and I have it implemented in a local build. See the screenshots below and tell me what you think. I have a few more tests to do but I should have this update out by tomorrow.

![Screen 1](http://img.skitch.com/20100516-nyabymeg681fsc3dj94pn3r7bu.png)

![Screen 2](http://img.skitch.com/20100516-phrh4ay1jhkhpe49na53k9dbp6.png)

**Comment by windrag** [comment]
Looks great!

**Comment by nrj** [comment]
Released in 0.5.2 today.
