### ISSUE TITLE
Support for Amazon S3 Uploads

### ISSUE THREAD

**Issue by nrj** [nrj/OneWay#19]
I've been working on this, you can expect to see it in an update sometime next week.

**Comment by notmyname** [comment]
Any possibility to get Rackspace Cloud FIles, too?

**Comment by nrj** [comment]
At somepoint yes. Right now though the most requested support is for SCP, and S3, so I am working on getting those implemented first.

**Comment by nrj** [comment]
This is in 0.5.4 - will be publishing momentarily.
